# File: muj code/backend/docker-compose.yml
version: '3.8'
services:
  # 1. MongoDB (Problems aur Submissions ke liye)
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # 2. Redis (Job Queue ke liye - Zaroori hai)
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  # 3. PostgreSQL (Users aur Auth ke liye)
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mujcode
    ports:
      - "5432:5432"

volumes:
  mongo_data:
